export * as authApi from "./auth";
export * as employeesApi from "./employees";
export * as directionsApi from "./directions";
export * as departmentsApi from "./departments";
export * as attendanceApi from "./attendance";
export * as badgesApi from "./badges";
export * as devicesApi from "./devices";
export * as schedulesApi from "./schedules";
export * as leavesApi from "./leaves";
export * as permissionsApi from "./permissions";
export * as absencesApi from "./absences";
export * as planningApi from "./planning";
export * as meetingsApi from "./meetings";
export * as notificationsApi from "./notifications";
export * as reportsApi from "./reports";
export * as usersApi from "./users";
export * as referenceDataApi from "./referenceData";
export * as approvalsApi from "./approvals";
export * as auditLogsApi from "./auditLogs";

export { ApiError, apiRequest, get, patch, post, remove, upload } from "./client";
export type { Query, RequestOptions } from "./client";