import {defineAsyncComponent} from 'vue'

const icons = {
  HomeIcon: () => import('./HomeIcon.vue'),
  UsersIcon: () => import('./UsersIcon.vue'),
  BuildingOfficeIcon: () => import('./BuildingOfficeIcon.vue'),
  ClockIcon: () => import('./ClockIcon.vue'),
  CheckCircleIcon: () => import('./CheckCircleIcon.vue'),
  CalendarDaysIcon: () => import('./CalendarDaysIcon.vue'),
  QrCodeIcon: () => import('./QrCodeIcon.vue'),
  UserCircleIcon: () => import('./UserCircleIcon.vue'),
  Cog6ToothIcon: () => import('./Cog6ToothIcon.vue'),
  ArrowRightOnRectangleIcon: () => import('./ArrowRightOnRectangleIcon.vue'),
  PlusIcon: () => import('./PlusIcon.vue'),
  MagnifyingGlassIcon: () => import('./MagnifyingGlassIcon.vue'),
  PencilIcon: () => import('./PencilIcon.vue'),
  TrashIcon: () => import('./TrashIcon.vue'),
  EyeIcon: () => import('./EyeIcon.vue'),
  DownloadIcon: () => import('./DownloadIcon.vue'),
  PrinterIcon: () => import('./PrinterIcon.vue'),
  RefreshIcon: () => import('./RefreshIcon.vue'),
  ExclamationCircleIcon: () => import('./ExclamationCircleIcon.vue'),
  CheckBadgeIcon: () => import('./CheckBadgeIcon.vue'),
  XCircleIcon: () => import('./XCircleIcon.vue'),
  ArrowPathIcon: () => import('./ArrowPathIcon.vue'),
  DocumentTextIcon: () => import('./DocumentTextIcon.vue'),
  ArrowDownTrayIcon: () => import('./ArrowDownTrayIcon.vue'),
  ArrowUpTrayIcon: () => import('./ArrowUpTrayIcon.vue'),
  BellIcon: () => import('./BellIcon.vue'),
  ChevronDownIcon: () => import('./ChevronDownIcon.vue'),
  ChevronLeftIcon: () => import('./ChevronLeftIcon.vue'),
  ChevronRightIcon: () => import('./ChevronRightIcon.vue'),
  Bars3Icon: () => import('./Bars3Icon.vue'),
  XMarkIcon: () => import('./XMarkIcon.vue'),
  MailIcon: () => import('./MailIcon.vue'),
}

export const HomeIcon = defineAsyncComponent(icons.HomeIcon)
export const UsersIcon = defineAsyncComponent(icons.UsersIcon)
export const BuildingOfficeIcon = defineAsyncComponent(icons.BuildingOfficeIcon)
export const ClockIcon = defineAsyncComponent(icons.ClockIcon)
export const CheckCircleIcon = defineAsyncComponent(icons.CheckCircleIcon)
export const CalendarDaysIcon = defineAsyncComponent(icons.CalendarDaysIcon)
export const QrCodeIcon = defineAsyncComponent(icons.QrCodeIcon)
export const UserCircleIcon = defineAsyncComponent(icons.UserCircleIcon)
export const Cog6ToothIcon = defineAsyncComponent(icons.Cog6ToothIcon)
export const ArrowRightOnRectangleIcon = defineAsyncComponent(icons.ArrowRightOnRectangleIcon)
export const PlusIcon = defineAsyncComponent(icons.PlusIcon)
export const MagnifyingGlassIcon = defineAsyncComponent(icons.MagnifyingGlassIcon)
export const PencilIcon = defineAsyncComponent(icons.PencilIcon)
export const TrashIcon = defineAsyncComponent(icons.TrashIcon)
export const EyeIcon = defineAsyncComponent(icons.EyeIcon)
export const DownloadIcon = defineAsyncComponent(icons.DownloadIcon)
export const PrinterIcon = defineAsyncComponent(icons.PrinterIcon)
export const RefreshIcon = defineAsyncComponent(icons.RefreshIcon)
export const ExclamationCircleIcon = defineAsyncComponent(icons.ExclamationCircleIcon)
export const CheckBadgeIcon = defineAsyncComponent(icons.CheckBadgeIcon)
export const XCircleIcon = defineAsyncComponent(icons.XCircleIcon)
export const ArrowPathIcon = defineAsyncComponent(icons.ArrowPathIcon)
export const DocumentTextIcon = defineAsyncComponent(icons.DocumentTextIcon)
export const ArrowDownTrayIcon = defineAsyncComponent(icons.ArrowDownTrayIcon)
export const ArrowUpTrayIcon = defineAsyncComponent(icons.ArrowUpTrayIcon)
export const BellIcon = defineAsyncComponent(icons.BellIcon)
export const ChevronDownIcon = defineAsyncComponent(icons.ChevronDownIcon)
export const ChevronLeftIcon = defineAsyncComponent(icons.ChevronLeftIcon)
export const ChevronRightIcon = defineAsyncComponent(icons.ChevronRightIcon)
export const Bars3Icon = defineAsyncComponent(icons.Bars3Icon)
export const XMarkIcon = defineAsyncComponent(icons.XMarkIcon)
export const MailIcon = defineAsyncComponent(icons.MailIcon)
